name: google_maps_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  google_maps_flutter: ^2.2.4
  google_maps_flutter_android: ^2.4.6
  google_maps_flutter_platform_interface: ^2.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
